### PR TITLE
I changed some things.

### PR DESCRIPTION
**Pull request by shuxinqin**
1. Backpressure supported
2. Cancel supported
3. Fixes the bug of multi thread writing to pipewriter
4. Handling Application_Error
5. KeepAlive supported
I made a lot of changes in the API, and made part of API Obsoleted. I hope you will adopt it, thx.

### CODE REVIEW

**Comment by OlegDokuka** [comment]
@shuxinqin Thank you for sending this PR.

Unfortunately, this PR is too broad to get it and accept. Can you please improve the commits structure and ensure they have logical messages and explanations.

Thanks,
Oleh

**Comment by shuxinqin** [comment]
I've improved and added a lot of features, and I've done docking with rsocket-java. I submitted too many times in the development process, and now I can't roll back, sorry~

**Comment by OlegDokuka** [comment]
@shuxinqin how about scheduling a call and going through this changes then?

**Comment by shuxinqin** [comment]
I am modifying this project to support quic as the transport layer. When I'm free, I'll sort out some previous commit records and write enough unit tests.
Thank you for your reply!

**Pull request closed without merging**
